feature: bypass parsing/rendering of file diff if specific threshold is crossed
rtfpessoa/diff2html pull request #365
Opened 2021-02-25 19:40 UTC by Pierrci

This PR allows users to specify a `diffMaxChanges` threshold above which the diff parsing/rendering of a file is bypassed, and a message is rendered instead ("Diff too big to be displayed"). The threshold value is compared to the sum of added+deleted lines for each file diff.

The user can also pass a new `diffTooBigMessage` function in the options to fully customize the message in case of file diff too big. This function receives the file index in the diff as an argument. It can be used to render a link to the raw file diff for example.

Example of default side-by-side rendering:

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/5020707/109207476-275aae80-7777-11eb-972e-955a722d8dc4.png">

2021-02-25 20:36 UTC, Pierrci commented
Eager to hear and take into account any feedback you might have @rtfpessoa 🙏.
Also not sure why 2 checks are failing...

2021-02-28 21:35 UTC, rtfpessoa requested changes
Sorry for the delay but did not got much time to review earlier.
I left some comments, let me know if you need guidance with anything.

Do not worry about the checks for now.

2021-02-28 21:35 UTC, rtfpessoa commented on src/diff-parser.ts
> +    if (
Is there any reason for this logic to not be near the condition to skip the file?

2021-02-28 21:35 UTC, rtfpessoa commented on src/render-utils.ts
> +  diffTooBigMessage: (_fileIndex: number): string => 'Diff too big to be displayed',
```suggestion
  diffTooBigMessage: (): string => 'Diff too big to be displayed',
```

2021-02-28 21:35 UTC, rtfpessoa commented on src/render-utils.ts
> +  diffTooBigMessage: (_fileIndex: number): string => 'Diff too big to be displayed',
If you do not need the parameter you can not declare it

2021-02-28 21:35 UTC, rtfpessoa commented on website/templates/pages/demo/demo.ts
> +  // Removing `diff` and `diffTooBigMessage` form `urlParams` to avoid being inserted
Why are you removing this from the url?

2021-02-28 21:35 UTC, rtfpessoa commented on website/templates/pages/demo/demo.ts
> +  } as unknown) as URLParams;
This is not very interesting since `as` is super unsafe.

2021-02-28 21:35 UTC, rtfpessoa commented on src/diff-parser.ts
> +    if (
Also I would rather have this being all implemented in the parser instead of having part of the logic going to the html generator.
Can you try using the same logic as the `Binary file`, where we start a fake block with the contents?

2021-03-01 19:51 UTC, Pierrci commented on website/templates/pages/demo/demo.ts
> +  // Removing `diff` and `diffTooBigMessage` form `urlParams` to avoid being inserted
`diffTooBigMessage` is expected to be a function so it seems safer to me to omit it even if it's somehow present in the URL params since it wouldn't be parsed correctly anyway, but I can leave it if you prefer

2021-03-01 19:59 UTC, Pierrci commented
@rtfpessoa I tried to move all the logic in the parser as requested, getting some inspiration from the binary file case. Overall it simplifies everything, but I had to bypass the HTML escaping as a result for the file diff header in the 2 renderers to keep allowing for custom message/link.

Let me know what you think, I'll push an update for the tests if you're ok with the updated logic.

2021-03-01 20:01 UTC, Pierrci commented on website/templates/pages/demo/demo.ts
> +  } as unknown) as URLParams;
Agreed, but I couldn't find a simple and better way with `diffTooBigMessage` in the default config. Since it's not present there anymore I reverted it.

2021-03-01 20:22 UTC, rtfpessoa commented on website/templates/pages/demo/demo.ts
> +  // Removing `diff` and `diffTooBigMessage` form `urlParams` to avoid being inserted
That makes total sense. We should remove it.

2021-03-01 20:24 UTC, rtfpessoa commented
> I had to bypass the HTML escaping as a result for the file diff header in the 2 renderers to keep allowing for custom message/link.

That is definitely not amazing but we can live with it for now.

LGTM 👍, you can go ahead with the tests.

2021-03-01 21:07 UTC, Pierrci commented
Tests should be good now :)

2021-03-04 22:41 UTC, merged

2021-03-04 22:52 UTC, rtfpessoa commented
Released in https://github.com/rtfpessoa/diff2html/releases/tag/3.3.0

2021-03-04 22:57 UTC, Pierrci commented
Thank you very much for merging and the release @rtfpessoa! 🙏